name: Build Website

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    # Step 3: Build the website
    - name: Build Website
      run: hugo --minify

    # Step 4: Upload build artifacts (optional)
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: public/
